//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agensi.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserComment
    {
        public long CommentId { get; set; }
        public string FromUserId { get; set; }
        public string ToUserId { get; set; }
        public string Comment { get; set; }
        public int ViewFlag { get; set; }
        public System.DateTime AddTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
